### PR TITLE
post patch shenanigans

### PR DESCRIPTION
**Pull request by bsips**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I've _**tested my code and the things my code has changed**_ since the last commit in the PR, and will test after any later commits

## What does this pull request do?

-fixes issue where ooe_mob_drops.sql doesnt run on update
-removes speed belt from simurgh and replaces with trotter (RA/EX) boots
-replaces various drops in the TR droplist module to their RA/EX versions
-added module to swap RA/EX drops with RA only (pre rmt drops)
-reorders modules to apply TR drops with %'s (standard RA/EX versions) then optionally swap them with their rare versions with a follow up module on Init. This will make reverting back to RA/EX much easier down the road if ever needed.

## Steps to test these changes

-run DB tool bay-Bee

### CODE REVIEW

**Comment by bsips** [comment]
-fixes issue where `ooe_mob_drops.sql` doesnt run on update

**Comment by bsips** [comment]
le comb

**Comment by xammy0** [comment]
I can't figure it out, are Archer's Rings available now or Shikaree's?

**Comment by bsips** [comment]
> I can't figure it out, are Archer's Rings available now or Shikaree's?

The `rare_NM_drops.sql` module loading at the end of init will make archers the drop.

**Review by austinclprojects — APPROVED** [review]

**Pull request merged**
